---
- hosts: localhost

  vars_prompt:

  - name: have_gcp_account
    prompt: Do you have a Google Cloud Platform (GCP) account already and gcloud on the CLI configured? (yes|no)?
    default: "yes"
    private: no

  - name: have_dockerhub_account
    prompt: Do you have a Docker Hub account and are logged in with "docker login" on the cli (yes|no)?
    default: "yes"
    private: no

  - name: docker_hub_name
    prompt: What is your docker hub name? Determine this by going to https://hub.docker.com and it will be in the top right corner.
    private: no

  tasks:

  # TODO more direction needed here for making the service account
  - name: verify answer for have_gcp_account
    fail:
      msg: Please go to https://console.developers.google.com/ and create one
    when: have_gcp_account != "yes"

  - name: verify answer for have_dockerhub_account
    fail:
      msg: Please go to https://hub.docker.com and create one, and then run "docker login" on the cli.
    when: have_dockerhub_account != "yes"

  - name: verify answer for docker_hub_name
    fail:
      msg: Please go to https://hub.docker.com to determine your username.
    when: docker_hub_name|length < 3

  # to get this far, git and ansible have to already been installed so the shell wrapper needs to have the checks there, not here
  - name: check for prerequisites on cli $PATH, if a failure please try to brew/yum/apt-get install the package
    changed_when: false
    command: which {{ item.name }}
    loop:
      - { name: 'docker' }
      - { name: 'gcloud' }
      - { name: 'go' }
      - { name: 'kubectl' }
      - { name: 'terraform' }
      - { name: 'foo' }
# TODO ansible_failed_result - https://docs.ansible.com/ansible/latest/user_guide/playbooks_blocks.html, can we tell the user the exact item that failed?

#  - name: verify GCP json account information

  # http://www.mydailytutorials.com/working-date-timestamp-ansible/
  # tell user the time as the next command can take a long while
  - name: the time is now
    debug:
      var=ansible_date_time.time

  - name: run terraform to setup GCP k8 cluster, THIS COMMAND TAKES UP TO 8 MINUTES, if it fails please ensure the service account in terraform/account.json has enough rights to create gcp kubernetes clusters
    terraform:
      project_path: '../terraform/'
      state: present

  # no built in ansible modules for golang, didn't check for quality of galaxy
  # TODO this is not idempodent, what is the cleanest thing we can do here, md5sum check?
  - name: build golang binary for linux amd64
    changed_when: false
    command: env GOOS=linux GOARCH=amd64 go build -o ../code/code.bin ../code/main.go

  - name: build docker image
    docker_image:
      build:
        path: ../code/
      name: kylesloan/automate-all-the-things
      tag: latest
      push: yes
      source: build

  # TODO is there ansible gcloud module?
  - name: load new cluster into profile
    command: gcloud container clusters get-credentials my-gke-cluster --region us-central1
    changed_when: false

  - name: create custom deployment.yml for k8 with docker hub account
    template:
      src=deploy.yml.j2
      dest=../k8/deploy.yml
    delegate_to: localhost

  # TODO pip install openshift
  # this seems to be a bug, even after installing and running a command: pip list, i can see openshift is installed and ansible is using it
  # so go with regular command at this point
  - name: run kubenetes deployment yamls
    changed_when: false
    command: kubectl apply -f ../k8/{{ item.file }}
    with_items:
      - { file: 'deploy.yml' }
      - { file: 'service.yml' }
      - { file: 'ingress.yml' }

  - name: the time is now
    debug:
      var=ansible_date_time.time

  - name: see if the ingress load balancer exists from a previous run and already has an IP
    changed_when: false
    register: r
    raw: "kubectl get ingress automate-all-the-things-ingress --output jsonpath='{.status.loadBalancer.ingress[0].ip}'"

  - name: sleep for a bit and try to get the GCP public IP for the new load balancer, this process takes a long time, even after the IP is allocated, it takes another few minutes to reach the cluster, SLEEP 3 MINS
    when: r.stdout == ""
    changed_when: false
    register: r2
    raw: "sleep 180; kubectl get ingress automate-all-the-things-ingress --output jsonpath='{.status.loadBalancer.ingress[0].ip}'"

  - name: "GCP load balancer creation can take up to 15 minutes to add the IP address and properly sync with the k8 cluster, here is the command that should end up working.  You might want to login to GCP console and go to Kube Engine: Services & Ingress to monitor how the load balancer is progressing"
    debug: msg="curl -iL http://{% if r2.stdout is defined %}{{ r2.stdout }}{% else %}{{ r.stdout }}{% endif %}/"

  - name: Debug directions while you wait for GCP to finish the Ingress Load balancer setup, launch another container into the cluster and curl the service
    debug: msg="kubectl run -i --tty ubuntu --image=ubuntu:16.04 --restart=Never -- bash -il"

  - name: Install curl
    debug: msg="apt update && apt install -y curl iputils-ping host"

  - name: curl the service internally
    debug: msg="curl -iL automate-all-the-things-service:8081"
